name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # needed so Sonar can compare branches/PRs

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"  # adjust if your ComfyUI fork needs a different version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # install your project dependencies here.
          # ComfyUI doesn't always ship a standard requirements.txt,
          # so adapt this to however you normally set up the env.
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest pytest-cov

      - name: Run tests with coverage
        run: |
          pytest --cov=. --cov-report xml:coverage.xml --cov-report term

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
        with:
          args: >
            -Dsonar.organization=myprojectsmaja
            -Dsonar.projectKey=myprojectsmaja_capstonecomfyui
            -Dsonar.python.coverage.reportPaths=coverage.xml
